project:
  type: website
  output-dir: docs
  render:
    - W4_presentation.qmd

website:
  title: "W4. Ego Network Data"
  site-url: "https://ComputationalSociologyLab.github.io/SNA_fall_2025"

metadata-files:
  - _metadata.yml

format:
  revealjs:
    theme: default

