<!DOCTYPE html>
<html lang="en"><head>
<script src="W4_presentation_files/libs/clipboard/clipboard.min.js"></script>
<script src="W4_presentation_files/libs/quarto-html/tabby.min.js"></script>
<script src="W4_presentation_files/libs/quarto-html/popper.min.js"></script>
<script src="W4_presentation_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="W4_presentation_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="W4_presentation_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="W4_presentation_files/libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.24">

  <title>W4. Ego Network Data</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="W4_presentation_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="W4_presentation_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="W4_presentation_files/libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link href="W4_presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="W4_presentation_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="W4_presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="W4_presentation_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">W4. Ego Network Data</h1>

<div class="quarto-title-authors">
</div>

</section>
<section>
<section id="ch6-Ego-Network-Data-R" class="title-slide slide level1 center">
<h1>Ego Network Data</h1>
<ul>
<li><p>Cover the basics of ego network data, utilizing the <strong>egor</strong> package</p></li>
<li><p>Construct and visualize ego networks</p></li>
<li><p>Focus on substantive questions related to homophily</p></li>
</ul>
</section>
<section id="working-with-ego-network-data" class="slide level2">
<h2>Working with Ego Network Data</h2>
<ul>
<li><p>Ego network data are based on a sample of individuals and are commonly used in the social sciences.</p></li>
<li><p>Each respondent (ego) reports on the people (alters) they are connected to, providing the local network around the focal respondent.</p></li>
<li><p>Ego network data offer only pieces of the whole network</p></li>
</ul>
</section>
<section id="working-with-ego-network-data-1" class="slide level2">
<h2>Working with Ego Network Data</h2>
<ul>
<li><p>Ego network data can be structured in a number of ways but will generally have 4 kinds of information:</p>
<ul>
<li><p>1, demographic, behavioral, etc. information on the egos</p></li>
<li><p>2, demographic, behavioral, etc. information on the named alters</p></li>
<li><p>3, information about the relationship between ego and alter</p></li>
<li><p>4, information about the relationships between the alters.</p></li>
</ul></li>
</ul>
</section>
<section id="working-with-ego-network-data-2" class="slide level2">
<h2>Working with Ego Network Data</h2>
<ul>
<li><p>Work with ego network data from the GSS(General Social Survey)</p>
<ul>
<li><p>a file with the ego attributes</p></li>
<li><p>a file with the alter(other) attributes</p></li>
<li><p>a file with the alter-alter ties</p></li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="co"># a file with the ego attributes</span></span>
<span id="cb1-2"><a href=""></a>url1 <span class="ot">&lt;-</span> <span class="st">"https://github.com/JeffreyAlanSmith/Integrated_Network_Science/raw/master/data/gss1985_ego_dat.csv"</span></span>
<span id="cb1-3"><a href=""></a></span>
<span id="cb1-4"><a href=""></a>ego_dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> url1, <span class="at">stringsAsFactors =</span> F) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="load-dataset-for-ego-attribute" class="slide level2">
<h2>Load Dataset for Ego Attribute</h2>
<p>First 10 rows of the ego data frame</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a><span class="co"># CASEID : unique ID for each respondent</span></span>
<span id="cb2-2"><a href=""></a><span class="co"># NUMGIVEN : the number of alters named</span></span>
<span id="cb2-3"><a href=""></a>ego_dat[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="fu">c</span>(<span class="st">"CASEID"</span>, <span class="st">"AGE"</span>, <span class="st">"EDUC"</span>, <span class="st">"RACE"</span>, <span class="st">"SEX"</span>, <span class="st">"HAPPY"</span>, <span class="st">"NUMGIVEN"</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     CASEID AGE EDUC  RACE    SEX HAPPY NUMGIVEN
1  19850001  33   16 white   male     2        6
2  19850002  49   19 white   male     2        6
3  19850003  23   16 white female     2        5
4  19850004  26   20 white female     2        5
5  19850005  24   17 white female     2        5
6  19850006  45   17 white   male     2        4
7  19850007  44   18 white female     2        6
8  19850008  56   12 white female     2        5
9  19850009  85    7 white female     2        2
10 19850010  65   12 white female     2        2</code></pre>
</div>
</div>
</section>
<section id="load-dataset-for-ego-attribute-1" class="slide level2">
<h2>Load Dataset for Ego Attribute</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a><span class="co"># check if there is empty values</span></span>
<span id="cb4-2"><a href=""></a>na_yn <span class="ot">&lt;-</span><span class="sc">!</span><span class="fu">is.na</span>(ego_dat<span class="sc">$</span>NUMGIVEN)</span>
<span id="cb4-3"><a href=""></a><span class="co"># exclude the emply values</span></span>
<span id="cb4-4"><a href=""></a>ego_dat <span class="ot">&lt;-</span> ego_dat[na_yn, ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="load-dataset-for-alter-attribute" class="slide level2">
<h2>Load Dataset for Alter Attribute</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>url2 <span class="ot">&lt;-</span> <span class="st">"https://github.com/JeffreyAlanSmith/Integrated_Network_Science/raw/master/data/gss1985_alter_dat.csv"</span></span>
<span id="cb5-2"><a href=""></a></span>
<span id="cb5-3"><a href=""></a>alter_dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> url2, <span class="at">stringsAsFactors =</span> F)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="load-dataset-for-alter-attribute-1" class="slide level2">
<h2>Load Dataset for Alter Attribute</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a><span class="co"># each row corresponds to a different named alter</span></span>
<span id="cb6-2"><a href=""></a><span class="co"># Each alter is denoted by an ALTERID (CASEID : ALTERID = 1:N)</span></span>
<span id="cb6-3"><a href=""></a><span class="co"># KIN : 1(True) if ego is relatives with that alter</span></span>
<span id="cb6-4"><a href=""></a><span class="co"># respondent 1 (CASEID = 19850001) names 5 alters. The first alter (ALTERID = 1) is 32, has 18 years of education, and is not kin to ego.</span></span>
<span id="cb6-5"><a href=""></a>alter_dat[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="fu">c</span>(<span class="st">"CASEID"</span>, <span class="st">"ALTERID"</span>, <span class="st">"AGE"</span>, <span class="st">"EDUC"</span>, <span class="st">"RACE"</span>, <span class="st">"SEX"</span>, <span class="st">"KIN"</span>)] </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     CASEID ALTERID AGE EDUC  RACE    SEX KIN
1  19850001       1  32   18 white   male   0
2  19850001       2  29   16 white female   1
3  19850001       3  32   18 white   male   0
4  19850001       4  35   16 white   male   1
5  19850001       5  29   13 white female   0
6  19850002       1  42   12 white female   1
7  19850002       2  44   18 white   male   0
8  19850002       3  45   16 white   male   0
9  19850002       4  40   12 white female   0
10 19850002       5  50   18 white   male   0</code></pre>
</div>
</div>
</section>
<section id="load-dataset-for-alter-alter-tie" class="slide level2">
<h2>Load Dataset for Alter-Alter Tie</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href=""></a>url3 <span class="ot">&lt;-</span> <span class="st">"https://github.com/JeffreyAlanSmith/Integrated_Network_Science/raw/master/data/gss1985_alteralter_dat.csv"</span></span>
<span id="cb8-2"><a href=""></a></span>
<span id="cb8-3"><a href=""></a>alteralter_dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> url3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="load-dataset-for-alter-alter-tie-1" class="slide level2">
<h2>Load Dataset for Alter-Alter Tie</h2>
<ul>
<li>the ties between the named alters</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a><span class="co"># `CASEID` : relevant ego </span></span>
<span id="cb9-2"><a href=""></a><span class="co"># `ALTER1` : first alter in the dyad</span></span>
<span id="cb9-3"><a href=""></a><span class="co"># `ALTER2` : second alter in the dyad</span></span>
<span id="cb9-4"><a href=""></a><span class="co"># `Weight` : nature of the relationship (1 : alters know each other, 2: especially close)</span></span>
<span id="cb9-5"><a href=""></a>alteralter_dat[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     CASEID ALTER1 ALTER2 WEIGHT
1  19850001      1      2      2
2  19850001      1      3      1
3  19850001      1      4      1
4  19850001      1      5      1
5  19850001      2      3      2
6  19850001      2      4      2
7  19850001      2      5      2
8  19850001      3      4      1
9  19850001      3      5      1
10 19850001      4      5      1</code></pre>
</div>
</div>
</section>
<section id="lets-make-ego-network" class="slide level2">
<h2>Let’s make Ego Network</h2>
<ul>
<li>The first challenge in analyzing ego network data is that we must transform traditional survey data into something that has the structure of a network, so that we can then utilize packages like igraph and sna.</li>
<li>Our survey data will not look like traditional network inputs (matrices, edgelists, etc.) and each survey is likely to be different, complicating the task of putting together the ego networks.</li>
<li>Luckily, the <strong>egor</strong> package has made the task of constructing ego networks from survey data much easier. We will utilize the basic functionality of the <strong>egor</strong> package throughout the tutorial. Let’s go ahead and load the package.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href=""></a><span class="co"># load a package for constructing ego network</span></span>
<span id="cb11-2"><a href=""></a><span class="fu">library</span>(egor)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="lets-make-ego-network-1" class="slide level2">
<h2>Let’s make Ego Network</h2>
<ul>
<li>The basic idea is to first construct an egor object from the survey data.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href=""></a><span class="co"># The function we will use to construct the egor object is `egor()`. The `egor()` function assumes that you are inputting the data using three separate files.</span></span>
<span id="cb12-2"><a href=""></a>egonetlist <span class="ot">&lt;-</span>  <span class="fu">egor</span>(<span class="at">alters =</span> alter_dat, <span class="co"># alter attributes data frame</span></span>
<span id="cb12-3"><a href=""></a>                    <span class="at">egos =</span> ego_dat, <span class="co"># ego attributes data frame</span></span>
<span id="cb12-4"><a href=""></a>                    <span class="at">aaties =</span> alteralter_dat, <span class="co"># alter-alter tie data frame</span></span>
<span id="cb12-5"><a href=""></a>                    <span class="at">alter_design =</span> <span class="fu">list</span>(<span class="at">max =</span> <span class="dv">5</span>), <span class="co"># list of arguments to specify nomination information from survey</span></span>
<span id="cb12-6"><a href=""></a>                    <span class="co"># list of variable names corresponding to key columns</span></span>
<span id="cb12-7"><a href=""></a>                    <span class="at">ID.vars =</span> <span class="fu">list</span>(<span class="at">ego =</span> <span class="st">"CASEID"</span>, <span class="at">alter =</span><span class="st">"ALTERID"</span>, </span>
<span id="cb12-8"><a href=""></a>                                   <span class="at">source =</span> <span class="st">"ALTER1"</span>, <span class="at">target =</span> <span class="st">"ALTER2"</span>) </span>
<span id="cb12-9"><a href=""></a>                    ) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="lets-make-ego-network-2" class="slide level2">
<h2>Let’s make Ego Network</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href=""></a>egonetlist</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># EGO data (active): 1,531 × 13
  .egoID   AGE  EDUC RACE  SEX   RELIG AGE_CATEGORICAL EDUC_CATEGORICAL NUMGIVEN
*  &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;           &lt;chr&gt;               &lt;int&gt;
1 1.99e7    33    16 white male  jewi… 30s             College                 6
2 1.99e7    49    19 white male  cath… 40s             Post Graduate           6
3 1.99e7    23    16 white fema… jewi… 20s             College                 5
4 1.99e7    26    20 white fema… jewi… 20s             Post Graduate           5
5 1.99e7    24    17 white fema… cath… 20s             Post Graduate           5
# ℹ 1,526 more rows
# ℹ 4 more variables: HAPPY &lt;int&gt;, HEALTH &lt;int&gt;, PARTYID &lt;int&gt;, WTSSALL &lt;dbl&gt;
# ALTER data: 4,483 × 12
  .altID   .egoID   AGE  EDUC RACE  SEX   RELIG AGE_CATEGORICAL EDUC_CATEGORICAL
*  &lt;int&gt;    &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;           &lt;chr&gt;           
1      1 19850001    32    18 white male  jewi… 30s             Post Graduate   
2      2 19850001    29    16 white fema… prot… 20s             College         
3      3 19850001    32    18 white male  jewi… 30s             Post Graduate   
# ℹ 4,480 more rows
# ℹ 3 more variables: TALKTO &lt;int&gt;, SPOUSE &lt;int&gt;, KIN &lt;int&gt;
# AATIE data: 4,880 × 4
    .egoID .srcID .tgtID WEIGHT
*    &lt;int&gt;  &lt;int&gt;  &lt;int&gt;  &lt;int&gt;
1 19850001      1      2      2
2 19850001      1      3      1
3 19850001      1      4      1
# ℹ 4,877 more rows</code></pre>
</div>
</div>
</section>
<section id="lets-make-ego-network-3" class="slide level2">
<h2>Let’s make Ego Network</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href=""></a><span class="fu">names</span>(egonetlist) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "ego"   "alter" "aatie"</code></pre>
</div>
</div>
</section>
<section id="calculate-summary-statistics" class="slide level2">
<h2>Calculate Summary Statistics</h2>
<ul>
<li>We will begin with density, showing the proportion of alter-alter ties that exist in each ego network</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a><span class="co"># use `ego_density()` function</span></span>
<span id="cb17-2"><a href=""></a>dens <span class="ot">&lt;-</span> <span class="fu">ego_density</span>(egonetlist)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="calculate-summary-statistics-1" class="slide level2">
<h2>Calculate Summary Statistics</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href=""></a><span class="fu">head</span>(dens)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
    .egoID density
     &lt;int&gt;   &lt;dbl&gt;
1 19850001   1    
2 19850002   0.8  
3 19850003   0.6  
4 19850004   0.6  
5 19850005   1    
6 19850006   0.667</code></pre>
</div>
</div>
</section>
<section id="calculate-summary-statistics-2" class="slide level2">
<h2>Calculate Summary Statistics</h2>
<p>The density scores are stored in the object as <code>density</code>. For example, respondent 1 (19850001) has 5 alters and all 10 possible ties exist (density = 1), while respondent 2 (1950002) has 5 alters but only 8 ties exist (density = .8). To check:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href=""></a>alteralter_dat[alteralter_dat<span class="sc">$</span>CASEID <span class="sc">==</span> <span class="dv">19850001</span>, ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     CASEID ALTER1 ALTER2 WEIGHT
1  19850001      1      2      2
2  19850001      1      3      1
3  19850001      1      4      1
4  19850001      1      5      1
5  19850001      2      3      2
6  19850001      2      4      2
7  19850001      2      5      2
8  19850001      3      4      1
9  19850001      3      5      1
10 19850001      4      5      1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href=""></a>alteralter_dat[alteralter_dat<span class="sc">$</span>CASEID <span class="sc">==</span> <span class="dv">19850002</span>, ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     CASEID ALTER1 ALTER2 WEIGHT
11 19850002      1      2      1
12 19850002      1      3      1
13 19850002      1      4      2
14 19850002      1      5      2
15 19850002      2      4      2
16 19850002      3      4      2
17 19850002      3      5      1
18 19850002      4      5      2</code></pre>
</div>
</div>
</section>
<section id="plotting-ego-networks" class="slide level2">
<h2>Plotting Ego Networks</h2>
<ul>
<li>go over how to plot the ego networks using packages like <strong>igraph</strong></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href=""></a><span class="fu">library</span>(igraph)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="plotting-ego-networks-1" class="slide level2">
<h2>Plotting Ego Networks</h2>
<ul>
<li>convert the egor object to igraph objects.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href=""></a>igraph_nets <span class="ot">&lt;-</span> <span class="fu">as_igraph</span>(egonetlist)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="plotting-ego-networks-2" class="slide level2">
<h2>Plotting Ego Networks</h2>
<p>Now, let’s take a look at the first three ego networks.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href=""></a>igraph_nets[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>] </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$`19850001`
IGRAPH 61c1b66 UN-- 5 10 -- 
+ attr: .egoID (g/n), name (v/c), AGE (v/n), EDUC (v/n), RACE (v/c),
| SEX (v/c), RELIG (v/c), AGE_CATEGORICAL (v/c), EDUC_CATEGORICAL
| (v/c), TALKTO (v/n), SPOUSE (v/n), KIN (v/n), WEIGHT (e/n)
+ edges from 61c1b66 (vertex names):
 [1] 1--2 1--3 1--4 1--5 2--3 2--4 2--5 3--4 3--5 4--5

$`19850002`
IGRAPH fe09c91 UN-- 5 8 -- 
+ attr: .egoID (g/n), name (v/c), AGE (v/n), EDUC (v/n), RACE (v/c),
| SEX (v/c), RELIG (v/c), AGE_CATEGORICAL (v/c), EDUC_CATEGORICAL
| (v/c), TALKTO (v/n), SPOUSE (v/n), KIN (v/n), WEIGHT (e/n)
+ edges from fe09c91 (vertex names):
[1] 1--2 1--3 1--4 1--5 2--4 3--4 3--5 4--5

$`19850003`
IGRAPH ea7f1da UN-- 5 6 -- 
+ attr: .egoID (g/n), name (v/c), AGE (v/n), EDUC (v/n), RACE (v/c),
| SEX (v/c), RELIG (v/c), AGE_CATEGORICAL (v/c), EDUC_CATEGORICAL
| (v/c), TALKTO (v/n), SPOUSE (v/n), KIN (v/n), WEIGHT (e/n)
+ edges from ea7f1da (vertex names):
[1] 1--2 1--3 1--4 2--3 2--4 3--4</code></pre>
</div>
</div>
</section>
<section id="plotting-ego-networks-3" class="slide level2">
<h2>Plotting Ego Networks</h2>
<p>Now, let’s plot a couple of example networks, focusing on the first 3 ego networks.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href=""></a><span class="co"># set 1 row, 3 column grid for visualization layout</span></span>
<span id="cb28-2"><a href=""></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>))</span>
<span id="cb28-3"><a href=""></a><span class="co"># draw graphs in igraph_nets variable</span></span>
<span id="cb28-4"><a href=""></a>purrr<span class="sc">::</span><span class="fu">walk</span>(igraph_nets[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], plot)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="W4_presentation_files/figure-revealjs/unnamed-chunk-18-1.png" width="960" class="r-stretch"></section>
<section id="plotting-ego-networks-4" class="slide level2">
<h2>Plotting Ego Networks</h2>
<ul>
<li>Let’s color the nodes based on gender</li>
<li>so we can get a sense of the level of gender homogeneity in these ego networks</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href=""></a><span class="co"># somewhat more difficult task than with a single network</span></span>
<span id="cb29-2"><a href=""></a><span class="co"># defind a function to set the color for each network</span></span>
<span id="cb29-3"><a href=""></a>plotfunc_colorgender <span class="ot">&lt;-</span> <span class="cf">function</span>(nets){ </span>
<span id="cb29-4"><a href=""></a>  <span class="co"># Arguments: </span></span>
<span id="cb29-5"><a href=""></a>  <span class="co"># nets: ego network of interest</span></span>
<span id="cb29-6"><a href=""></a>  </span>
<span id="cb29-7"><a href=""></a>  <span class="co"># extracting the attribute from the ego network:</span></span>
<span id="cb29-8"><a href=""></a>  cols <span class="ot">&lt;-</span> <span class="fu">vertex_attr</span>(nets, <span class="st">"SEX"</span>) </span>
<span id="cb29-9"><a href=""></a></span>
<span id="cb29-10"><a href=""></a>  <span class="co"># now we use an ifelse statement to set color,</span></span>
<span id="cb29-11"><a href=""></a>  <span class="co"># light sky blue if gender equals female, blue otherwise:</span></span>
<span id="cb29-12"><a href=""></a>  cols <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(cols <span class="sc">==</span> <span class="st">"female"</span>, <span class="st">"lightskyblue"</span>, <span class="st">"blue"</span>)</span>
<span id="cb29-13"><a href=""></a></span>
<span id="cb29-14"><a href=""></a>  <span class="co"># plotting ego network with nodes colored based on gender:</span></span>
<span id="cb29-15"><a href=""></a>  <span class="fu">plot</span>(nets, <span class="at">vertex.color =</span> cols) </span>
<span id="cb29-16"><a href=""></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="plotting-ego-networks-5" class="slide level2">
<h2>Plotting Ego Networks</h2>
<ul>
<li>Now let’s run <code>plotfunc_colorgender()</code> over the first three ego networks.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href=""></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>))</span>
<span id="cb30-2"><a href=""></a>purrr<span class="sc">::</span><span class="fu">walk</span>(igraph_nets[<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], plotfunc_colorgender)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="W4_presentation_files/figure-revealjs/unnamed-chunk-20-1.png" width="960" class="r-stretch"><p>We can see that the third ego network is homogenous in terms of gender, but the first two are quite heterogeneous. We also see different patterns of ties between the named alters. The first ego network is complete, with a tie between all alter-alter pairs. In contrast, the third ego network is less dense, with one alter (id = 5) completely disconnected from the rest of the alters.</p>
</section>
<section id="homophily-ego-alter-attributes" class="slide level2">
<h2>Homophily: Ego-Alter Attributes</h2>
<p>We now move to our substantive questions about the strength and patterning of homophily. We will focus on gender and racial homophily, comparing across kin and non-kin ties. The first part of the analysis (Section 6.3.1 and 6.3.2) will utilize the ego-alter information, looking at the level of similarity between ego and alter for each ego network.</p>
<h3 id="proportion-of-alters-matching-ego">Proportion of Alters Matching Ego</h3>
<p>We will begin by calculating ego-level summary measures. Our first measure of interest, calculated for each ego, is the proportion of alters that ego matches on for the attribute of interest. For example, if ego is male, what proportion of the named alters are also male?</p>
<p>The <strong>egor</strong> package has a number of built-in functions, like <code>ego_density()</code>, that make it easy to calculate summary statistics. In many cases, however, we will want to calculate a measure that is not currently included in <strong>egor</strong>. In this case, we can write our own function and then apply it to the egor object using a <code>comp_ply()</code> function (part of the <strong>egor</strong> package). That is what we will do here. Let’s first write a little function that will compare ego’s attribute to the attributes of the alters and calculate the proportion of times they match.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href=""></a>prop_same_function <span class="ot">&lt;-</span> <span class="cf">function</span>(alt.attr, ego.attr){</span>
<span id="cb31-2"><a href=""></a></span>
<span id="cb31-3"><a href=""></a>  <span class="co"># Arguments:</span></span>
<span id="cb31-4"><a href=""></a>  <span class="co"># alt.attr: alter attributes for a given ego</span></span>
<span id="cb31-5"><a href=""></a>  <span class="co"># ego.attr: ego attributes</span></span>
<span id="cb31-6"><a href=""></a></span>
<span id="cb31-7"><a href=""></a>  <span class="co"># taking ego attribute and comparing to alter </span></span>
<span id="cb31-8"><a href=""></a>  <span class="co"># attributes, summing up number of times they match</span></span>
<span id="cb31-9"><a href=""></a>  <span class="co"># ignoring missing data:</span></span>
<span id="cb31-10"><a href=""></a>  same <span class="ot">&lt;-</span> <span class="fu">sum</span>(ego.attr <span class="sc">==</span> alt.attr, <span class="at">na.rm =</span> T) </span>
<span id="cb31-11"><a href=""></a></span>
<span id="cb31-12"><a href=""></a>  <span class="co"># calculating proportion of ego-alter pairs that match:</span></span>
<span id="cb31-13"><a href=""></a>  <span class="co"># just for alters with no missing data</span></span>
<span id="cb31-14"><a href=""></a>  prop_same <span class="ot">&lt;-</span> same <span class="sc">/</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(alt.attr))</span>
<span id="cb31-15"><a href=""></a>  </span>
<span id="cb31-16"><a href=""></a>  <span class="co"># making sure if ego is missing, then prop_same is also missing</span></span>
<span id="cb31-17"><a href=""></a>  prop_same[<span class="fu">is.na</span>(ego.attr)] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb31-18"><a href=""></a>  </span>
<span id="cb31-19"><a href=""></a>  <span class="fu">return</span>(prop_same) </span>
<span id="cb31-20"><a href=""></a>} </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note that any ego with no alters or with missing data for the alter attributes will return an NA.</p>
<p>We start by looking at the gender variable for all ties, including both kin and non-kin ties. We will calculate the proportion matching on gender by using our function (<code>prop_same_function()</code>) within a <code>comp_ply()</code> function. The main arguments to <code>comp_ply()</code> are:</p>
<ul>
<li>the ego object</li>
<li>alt.attr = the alter attribute of interest</li>
<li>.f = the function of interest</li>
<li>ego.attr = the ego attribute of interest, if required</li>
</ul>
<p>Here the alter and ego attribute are <code>SEX</code> and the function of interest is <code>prop_same_function()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href=""></a>pmatch_sex <span class="ot">&lt;-</span> <span class="fu">comp_ply</span>(egonetlist, <span class="at">alt.attr =</span> <span class="st">"SEX"</span>, <span class="at">.f =</span> prop_same_function, </span>
<span id="cb32-2"><a href=""></a>                       <span class="at">ego.attr =</span> <span class="st">"SEX"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href=""></a><span class="fu">head</span>(pmatch_sex)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
    .egoID result
     &lt;int&gt;  &lt;dbl&gt;
1 19850001   0.6 
2 19850002   0.6 
3 19850003   1   
4 19850004   0.4 
5 19850005   0.4 
6 19850006   0.75</code></pre>
</div>
</div>
<p>With the <code>comp_ply()</code> function, the calculated values are stored as <code>result</code>. We can see that the first two respondents match with .6 of the alters and the third matches with all of the named alters. We can go back to the raw data to spot check that this is correct. For example, respondent 1 is male (<code>ego_dat[ego_dat$CASEID == 19850001, "SEX"]</code>) and has 3 male and 2 female alters (<code>alter_dat[alter_dat$CASEID == 19850001, "SEX"]</code>), thus matching with .6 of the alters.</p>
<p>Now, let’s do the same thing, but only consider ties that are based on kin relations. We still want to calculate homophily for gender, but we will only consider ego-alter pairs that have a kin tie. The first step is to create a new egor object that subsets the alter data to just those cases where a kin relation exists. Here, we will use a <code>subset()</code> function. The main inputs are the original egor object, the condition of interest and the unit to subset on. In this case, the condition of interest is where the <code>KIN</code> variable (on the alter attribute data frame) is equal to 1. The unit is the alter, as we only want to keep some of the alters (those with a kin tie to ego).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href=""></a>egonetlist_kin <span class="ot">&lt;-</span> <span class="fu">subset</span>(egonetlist, egonetlist[[<span class="st">"alter"</span>]]<span class="sc">$</span>KIN <span class="sc">==</span> <span class="dv">1</span>, </span>
<span id="cb35-2"><a href=""></a>                         <span class="at">unit =</span> <span class="st">"alter"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now we rerun our function as before, but use the kin-based egor object.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href=""></a>pmatch_sex_kin <span class="ot">&lt;-</span> <span class="fu">comp_ply</span>(egonetlist_kin, <span class="at">alt.attr =</span> <span class="st">"SEX"</span>, </span>
<span id="cb36-2"><a href=""></a>                           <span class="at">.f =</span> prop_same_function, <span class="at">ego.attr =</span> <span class="st">"SEX"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Here we do the same thing again, but for non-kin relations (so only keeping those alters with a non-kin tie to ego).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href=""></a>egonetlist_nonkin <span class="ot">&lt;-</span> <span class="fu">subset</span>(egonetlist, egonetlist[[<span class="st">"alter"</span>]]<span class="sc">$</span>KIN <span class="sc">==</span> <span class="dv">0</span>,</span>
<span id="cb37-2"><a href=""></a>                            <span class="at">unit =</span> <span class="st">"alter"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href=""></a>pmatch_sex_nonkin <span class="ot">&lt;-</span> <span class="fu">comp_ply</span>(egonetlist_nonkin, <span class="at">alt.attr =</span> <span class="st">"SEX"</span>, </span>
<span id="cb38-2"><a href=""></a>                              <span class="at">.f =</span> prop_same_function, <span class="at">ego.attr =</span> <span class="st">"SEX"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>And now let’s put those vectors together into a single data frame, just extracting the result part of the output.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href=""></a>sexdat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(pmatch_sex<span class="sc">$</span>result, pmatch_sex_kin<span class="sc">$</span>result, </span>
<span id="cb39-2"><a href=""></a>                     pmatch_sex_nonkin<span class="sc">$</span>result)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href=""></a><span class="fu">head</span>(sexdat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         pmatch_sex.result pmatch_sex_kin.result pmatch_sex_nonkin.result
19850001              0.60                   0.5                0.6666667
19850002              0.60                   0.0                0.7500000
19850003              1.00                   1.0                1.0000000
19850004              0.40                   NaN                0.4000000
19850005              0.40                   0.4                      NaN
19850006              0.75                   1.0                0.6666667</code></pre>
</div>
</div>
<p>Each row shows the proportion of alters who have the same gender as ego (one row for each ego). The second and third columns show the results for kin ties and non-kin ties only. Now, we will quickly do the same calculations for race and then compare the results with those for gender. The only inputs that change are the alter and ego attribute name.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href=""></a>pmatch_race <span class="ot">&lt;-</span> <span class="fu">comp_ply</span>(egonetlist, <span class="at">alt.attr =</span> <span class="st">"RACE"</span>, </span>
<span id="cb42-2"><a href=""></a>                        <span class="at">.f =</span> prop_same_function, <span class="at">ego.attr =</span> <span class="st">"RACE"</span>) <span class="co">#all alters</span></span>
<span id="cb42-3"><a href=""></a></span>
<span id="cb42-4"><a href=""></a>pmatch_race_kin <span class="ot">&lt;-</span> <span class="fu">comp_ply</span>(egonetlist_kin, <span class="at">alt.attr =</span> <span class="st">"RACE"</span>, </span>
<span id="cb42-5"><a href=""></a>                            <span class="at">.f =</span> prop_same_function, <span class="at">ego.attr =</span> <span class="st">"RACE"</span>) <span class="co">#kin</span></span>
<span id="cb42-6"><a href=""></a></span>
<span id="cb42-7"><a href=""></a>pmatch_race_nonkin <span class="ot">&lt;-</span> <span class="fu">comp_ply</span>(egonetlist_nonkin, <span class="at">alt.attr =</span> <span class="st">"RACE"</span>, </span>
<span id="cb42-8"><a href=""></a>                               <span class="at">.f =</span> prop_same_function, <span class="at">ego.attr =</span> <span class="st">"RACE"</span>) <span class="co">#nonkin</span></span>
<span id="cb42-9"><a href=""></a></span>
<span id="cb42-10"><a href=""></a>racedat <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(pmatch_race<span class="sc">$</span>result, pmatch_race_kin<span class="sc">$</span>result, </span>
<span id="cb42-11"><a href=""></a>                      pmatch_race_nonkin<span class="sc">$</span>result)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href=""></a><span class="fu">head</span>(racedat)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         pmatch_race.result pmatch_race_kin.result pmatch_race_nonkin.result
19850001                  1                      1                         1
19850002                  1                      1                         1
19850003                  1                      1                         1
19850004                  1                    NaN                         1
19850005                  1                      1                       NaN
19850006                  1                      1                         1</code></pre>
</div>
</div>
<p>Now, let’s do a simple summary over the columns in each data frame using the <code>apply()</code> function. <code>apply()</code> allows us to do a specified function for each column or row of a matrix (it will automatically be coerced into a matrix if it is a data frame). This is the equivalent of <code>lapply()</code> for matrices. Here we will set MARGIN to 2 to take a summary over the columns and set FUN (the function of interest) to summary.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href=""></a><span class="fu">apply</span>(sexdat, <span class="at">MARGIN =</span> <span class="dv">2</span>, <span class="at">FUN =</span> summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        pmatch_sex.result pmatch_sex_kin.result pmatch_sex_nonkin.result
Min.            0.0000000             0.0000000                 0.000000
1st Qu.         0.4000000             0.0000000                 0.500000
Median          0.6000000             0.5000000                 1.000000
Mean            0.5917264             0.4647869                 0.738193
3rd Qu.         0.8000000             0.6666667                 1.000000
Max.            1.0000000             1.0000000                 1.000000
NA's          137.0000000           405.0000000               557.000000</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href=""></a><span class="fu">apply</span>(racedat, <span class="at">MARGIN =</span> <span class="dv">2</span>, <span class="at">FUN =</span> summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        pmatch_race.result pmatch_race_kin.result pmatch_race_nonkin.result
Min.             0.0000000              0.0000000                 0.0000000
1st Qu.          1.0000000              1.0000000                 1.0000000
Median           1.0000000              1.0000000                 1.0000000
Mean             0.9477834              0.9690074                 0.9294502
3rd Qu.          1.0000000              1.0000000                 1.0000000
Max.             1.0000000              1.0000000                 1.0000000
NA's           140.0000000            406.0000000               561.0000000</code></pre>
</div>
</div>
<p>We can see that there are clear differences by relation and demographic characteristic. Starting with gender, the mean value for proportion matching is .592. This value decreases to .465 for kin ties and increases to .738 for non-kin ties. Thus, individuals tend to have much more homogenous ego networks for gender in terms of non-kin ties. This follows as kin ties (such as marriage, parent-child, etc.) tend to cut across gender lines.</p>
<p>Race offers a very different story. The overall level of matching is quite high (over .9) and is actually a little higher in the kin case than in the non-kin case. This would suggest that racial/ethnic boundaries, while quite strong in this data, are a bit weaker in cases of friendship, etc. which extend beyond marital and family relations. More generally, we see that race is a much more salient dimension than gender, with many respondents matching perfectly with all members of their network along racial lines, but much less so with gender, where differences between ego and alter are more common.</p>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="W4_presentation_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="W4_presentation_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="W4_presentation_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="W4_presentation_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="W4_presentation_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="W4_presentation_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="W4_presentation_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="W4_presentation_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="W4_presentation_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="W4_presentation_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>